version: "3.8"

services:
  canoe:
    container_name: canoe
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: canoedb
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: canoeuser
      DATABASE_PASSWORD: Canoe123#
    restart: unless-stopped
    volumes:
      - ./:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: canoedb
      POSTGRES_USER: canoeuser
      POSTGRES_PASSWORD: Canoe123#
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  pg-data: